wip: v2
AdExNetwork/adex-protocol-eth pull request #118
Opened 2020-10-30 14:35 UTC by samparsky

2020-10-30 14:42 UTC, Ivshti requested changes

2020-10-30 14:42 UTC, Ivshti commented on contracts/v2/Outpace.sol
> +            require(now <= channel.validUntil, "EXPIRED");
we may be getting rid of that check: this is something that's described in the AIP

2020-10-30 14:42 UTC, Ivshti commented on contracts/v2/Outpace.sol
> +            if (bulkWithdraw.amountWithdrawnPerChannel.length > 0 && (bulkWithdraw.amountWithdrawnPerChannel.length - 1) > i) {
will explain this one in discord - matching by index won't work here

2021-01-05 16:16 UTC, Ivshti commented
Closing in favor of https://github.com/AdExNetwork/aips/issues/61

2021-01-05 16:16 UTC, closed without merging

2021-01-05 16:20 UTC, samparsky commented
ok, I will take a deeper look at it